"""
CropPulse – Reports Router
POST /api/v1/reports/generate   – Generate PDF report
GET  /api/v1/reports/           – List user's reports
GET  /api/v1/reports/{id}       – Get single report
"""

from fastapi import APIRouter, Depends, HTTPException, status
from loguru import logger

from backend.config import settings
from backend.dependencies import get_current_user
from backend.models.prediction import ReportRequest
from backend.services.report_service import report_service
from backend.services.mongodb_service import MongoDBService

router = APIRouter()

_report_svc = MongoDBService(settings.COLLECTION_REPORTS, id_field="report_id")


@router.post("/generate", status_code=status.HTTP_201_CREATED)
async def generate_report(
    payload: ReportRequest,
    current_user: dict = Depends(get_current_user),
):
    """
    Generate a PDF report for disease predictions, soil predictions, or combined.
    Uploads the PDF to GridFS and returns a public URL pointing to the file route.
    """
    uid = current_user["uid"]
    user_name = current_user.get("name", "Farmer")

    try:
        if payload.report_type == "disease":
            doc = await report_service.generate_disease_report(
                user_id=uid, user_name=user_name, farm_id=payload.farm_id
            )
        elif payload.report_type == "soil":
            doc = await report_service.generate_soil_report(
                user_id=uid, user_name=user_name, farm_id=payload.farm_id
            )
        elif payload.report_type == "combined":
            doc = await report_service.generate_combined_report(
                user_id=uid, user_name=user_name, farm_id=payload.farm_id
            )
        else:
            raise HTTPException(status_code=400, detail="Invalid report_type.")

        logger.info(f"Report generated: {doc.get('report_id')} | type={payload.report_type} | uid={uid}")
        return {**doc, "success": True}

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Report generation failed: {e}")
        raise HTTPException(status_code=500, detail=f"Report generation failed: {str(e)}")


@router.get("/")
async def list_reports(current_user: dict = Depends(get_current_user)):
    """Return all reports generated by the current user."""
    reports = await report_service.get_user_reports(current_user["uid"])
    return {"reports": reports, "total": len(reports)}


@router.get("/{report_id}")
async def get_report(report_id: str, current_user: dict = Depends(get_current_user)):
    """Return a single report record by ID."""
    doc = await _report_svc.get(report_id)
    if not doc:
        raise HTTPException(status_code=404, detail="Report not found.")
    if doc.get("user_id") != current_user["uid"] and current_user.get("role") != "admin":
        raise HTTPException(status_code=403, detail="Access denied.")
    return doc
